# This is a basic workflow to help you get started with Actions

name: CI


on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: ferhmdiogo@gmail.com
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Develop!
        
  deploy-homolog:
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: ferhmdiogo@gmail.com
    needs: deploy-develop
    steps:
      - name: Run a one-line script
        run: echo Deploy Homolog!
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ferhmdiogo@gmail.com
    needs: deploy-homolog
    steps:
      - name: Run a one-line script
        run: echo Deploy Prod!     
